# Lists of S&P 500 companies historical components

1. Read 'S&P 500 Historical Components & Changes.csv' which contains historical S&P 500 index membership since 1996.  Each row contains 2 fields: date and tickers; tickers is a comma delimited string of the symbols for that specified date.  This file was provided as open source via download for the book "Trading Evolved" by Andreas F. Clenow.  
2. Clean up the list by fixing up symbols, removing duplicates in each row, and sorting the symbols  
3. Read in 'sp500_changes_since_2019.csv' which contains the changes to the index since 2019  
4. Create new rows in the historical membership list for these changes  
5. Compare the last row to current list of S&P 500 components on the wikipedia  
6. A list of differences is generated.  If this list is NOT empty, then changes have been made to the index that should be included in 'sp500_changes_since_2019.csv'.  
7. Write out date stamped 'S&P 500 Historical Components & Changes' csv file

In [20]:
from datetime import datetime
import os
import pandas as pd

pd.options.mode.chained_assignment = None  # default='warn'
pd.set_option('display.max_rows', 600)

# -*- encoding: utf-8 -*-
%matplotlib inline

In [21]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [22]:
def get_table(filename):

    if os.path.isfile(filename):
        return pd.read_csv(filename, index_col='date')

In [23]:
filename = 'S&P 500 Historical Components & Changes.csv'
df = get_table(filename)
df.head()

                                                      tickers
date
1996-01-02  TMC-200006,AAL-199702,AAMRQ-201312,AAPL,ABI-20...
1996-01-03  AAL-199702,AAMRQ-201312,AAPL,ABI-200811,ABS-20...
1996-01-04  TMC-200006,AAL-199702,AAMRQ-201312,AAPL,OAT-20...
1996-01-10  TMC-200006,AAL-199702,AAMRQ-201312,AAPL,ABI-20...
1996-01-11  FLMIQ-200408,FLTWQ-200907,FMC,FMCC,FNMA,FTL.A-...

In [24]:
# Convert ticker column from csv to list, then sort.
df['tickers'] = df['tickers'].apply(lambda x: sorted(x.split(',')))
df.tail()

                                                      tickers
date
2019-01-03  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-08  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-09  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-10  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-11  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...

In [25]:
l = list(df['tickers'].head(100))[0]
l

['AAL-199702',
 'AAMRQ-201312',
 'AAPL',
 'ABI-200811',
 'ABS-200606',
 'ABT',
 'ABX',
 'ACKH-200211',
 'ACV-201105',
 'ADM',
 'ADP',
 'ADSK',
 'AEE',
 'AEP',
 'AET',
 'AGC-200108',
 'AGN-201503',
 'AHM-199810',
 'AIG',
 'AIT-199910',
 'AL-200711',
 'ALL',
 'AM-201308',
 'AMAT',
 'AMD',
 'AMGN',
 'AMH-199709',
 'AMP-199904',
 'AN-199812',
 'ANDW-200712',
 'ANV-199904',
 'APD',
 'AR-199911',
 'ARC-200004',
 'ARNC',
 'AS-199909',
 'ASC-199906',
 'ASH',
 'AT-200711',
 'ATI',
 'ATI-199906',
 'AVP',
 'AVY',
 'AXP',
 'AZA.A-200106',
 'BA',
 'BAC',
 'BAC-199809',
 'BAX',
 'BBI-199801',
 'BC',
 'BCO',
 'BCR-201712',
 'BDK-201003',
 'BDX',
 'BEAM-201404',
 'BEV-200603',
 'BF.B',
 'BFI-199907',
 'BFO-200010',
 'BGG',
 'BHGE',
 'BHMSQ-200401',
 'BK',
 'BKB-199909',
 'BLL',
 'BLS-200612',
 'BLY-199612',
 'BMET-200709',
 'BMS',
 'BMY',
 'BNI-201002',
 'BNL-199806',
 'BOAT-199701',
 'BOL-200710',
 'BR-200603',
 'BSX',
 'BT-199906',
 'BUD-200811',
 'C',
 'C-199811',
 'CA',
 'CAG',
 'CAL',
 'CAR',
 'CAT',
 'CB-201601',
 'CBB-199801',
 'CBE-201211',
 'CBS',
 'CBS-200005',
 'CCB-199602',
 'CCI-199810',
 'CCK',
 'CCTYQ-201009',
 'CEG-201203',
 'CEN-200711',
 'CFL-199804',
 'CG-200011',
 'CGP-200101',
 'CHA-200006',
 'CHRS-201206',
 'CI',
 'CIN-200603',
 'CL',
 'CLX',
 'CMA',
 'CMB-199603',
 'CMCSA',
 'CMI',
 'CNG-200001',
 'CNP',
 'CNW-201510',
 'COMS-201004',
 'COP',
 'COST',
 'COV-200203',
 'CPB',
 'CPQ-200205',
 'CR',
 'CRR-199706',
 'CSCO',
 'CSR-200006',
 'CSX',
 'CTB',
 'CTX-200908',
 'CVS',
 'CVX',
 'CYM-199912',
 'CYR-199606',
 'D',
 'DALRQ-200704',
 'DCNAQ-200801',
 'DD-201708',
 'DDS',
 'DE',
 'DEC-199806',
 'DGN-199910',
 'DI-199809',
 'DIGI-199809',
 'DIS',
 'DJ-200712',
 'DLX',
 'DOV',
 'DOW-201708',
 'DRI',
 'DTE',
 'DUK',
 'DWD-199705',
 'DXC',
 'EC-200606',
 'ECH-199807',
 'ECL',
 'ECO-200301',
 'ED',
 'EFU-200011',
 'EIX',
 'EKDKQ-201309',
 'EMN',
 'EMR',
 'ENRNQ-200411',
 'ENS-199708',
 'ETN',
 'ETR',
 'ETS-200603',
 'EXC',
 'F',
 'FBF-200403',
 'FBO-199603',
 'FCN-199810',
 'FCX',
 'FDC-200709',
 'FDX',
 'FE',
 'FG-199804',
 'FJ-200011',
 'FL',
 'FLMIQ-200408',
 'FLTWQ-200907',
 'FMC',
 'FMCC',
 'FNMA',
 'FTL.A-200004',
 'FWLT-201412',
 'G-200509',
 'GAPTQ-201203',
 'GAS-201112',
 'GD',
 'GDW-200609',
 'GE',
 'GFS.A-199810',
 'GIDL-199709',
 'GIS',
 'GLD-199705',
 'GLK-200507',
 'GLW',
 'GP-200512',
 'GPC',
 'GPS',
 'GPU-200111',
 'GR-201207',
 'GRA-199609',
 'GRN-199812',
 'GSX-199810',
 'GT',
 'GTE-200006',
 'GWF-199707',
 'GWW',
 'H-200107',
 'HAL',
 'HAS',
 'HCA-200611',
 'HD',
 'HDLM-201301',
 'HES',
 'HET-200801',
 'HI-200303',
 'HIG',
 'HLT-200710',
 'HM-200112',
 'HNZ-201306',
 'HON',
 'HON-199912',
 'HP',
 'HPC-200811',
 'HPH-199912',
 'HPQ',
 'HRB',
 'HRS',
 'HSH-201408',
 'HSY',
 'HUM',
 'I-199603',
 'IBM',
 'IFF',
 'IKN-200810',
 'INCLF-200701',
 'INGR-200611',
 'INTC',
 'IP',
 'IPG',
 'IR',
 'ITT',
 'ITT-199802',
 'ITW',
 'JAVA-201001',
 'JCI',
 'JCI-201609',
 'JCP',
 'JH-200705',
 'JNJ',
 'JOS-200005',
 'JP-200603',
 'JPM',
 'JPM-200012',
 'JWN',
 'K',
 'KATE-201707',
 'KBH',
 'KEY',
 'KM-200212',
 'KMB',
 'KMG-200608',
 'KO',
 'KR',
 'KRB-200512',
 'KRI-200606',
 'KWP-199911',
 'L',
 'LB',
 'LDG-200810',
 'LDW.B-200012',
 'LLX-199710',
 'LLY',
 'LMT',
 'LNC',
 'LOR-199604',
 'LOW',
 'LPX',
 'LSI-201405',
 'LUB',
 'LUV',
 'M',
 'MAS',
 'MAT',
 'MAY-200508',
 'MCD',
 'MCIC-199809',
 'MCO',
 'MD-199707',
 'MDP',
 'MDR',
 'MDT',
 'MEA-200201',
 'MEE-201106',
 'MEL-200706',
 'MER-200812',
 'MII-199906',
 'MIL-201007',
 'MKG-200010',
 'MMC',
 'MMM',
 'MNR-199809',
 'MO',
 'MOB-199911',
 'MRK',
 'MRO',
 'MS',
 'MSFT',
 'MSI',
 'MST-199808',
 'MTLQQ-201103',
 'MU',
 'MWI-200402',
 'MWV-201507',
 'MYG-200603',
 'MZIAQ-201010',
 'NAE-199708',
 'NAV',
 'NC',
 'NCC-200812',
 'NEE',
 'NEM',
 'NKE',
 'NLC-199912',
 'NMK-200201',
 'NOC',
 'NOVL-201104',
 'NRTLQ-201510',
 'NSC',
 'NSI-200306',
 'NSM-201109',
 'NUE',
 'NWL',
 'NYN-199708',
 'NYT',
 'OAT-200108',
 'OKE',
 'OM-199709',
 'OMX-201311',
 'ONE-200406',
 'ORCL',
 'ORX-199902',
 'OWENQ-200610',
 'OXY',
 'PAC-199703',
 'PAS-201002',
 'PBI',
 'PBY-201602',
 'PCAR',
 'PCG',
 'PCH',
 'PD-200703',
 'PDG-200603',
 'PEG',
 'PEL-199706',
 'PEP',
 'PET-199806',
 'PFE',
 'PG',
 'PGL-200702',
 'PGN-201207',
 'PH',
 'PHA-200304',
 'PHB-199910',
 'PHM',
 'PKI',
 'PLL-201508',
 'PMI-199911',
 'PNC',
 'PNU-200003',
 'PPG',
 'PPL',
 'PPW-199911',
 'PRD-200110',
 'PVN-199706',
 'PX',
 'PZE-199908',
 'R',
 'RAD',
 'RAL-200112',
 'RBD-199903',
 'RBK-200601',
 'RDC',
 'RDS.A',
 'RLM-200005',
 'RML-200608',
 'RNB-199912',
 'ROH-200904',
 'ROK',
 'RRD',
 'RSHCQ-201510',
 'RTN',
 'RYAN-200610',
 'RYC-199908',
 'RYI-200710',
 'S',
 'S-200503',
 'SAF-200809',
 'SB-199711',
 'SCI',
 'SFA-200602',
 'SFS-200008',
 'SGID-200610',
 'SGP-200911',
 'SHN-200007',
 'SHW',
 'SIAL-201511',
 'SK-199805',
 'SLB',
 'SMI-200109',
 'SMS-200007',
 'SNA',
 'SNT-199910',
 'SO',
 'SPGI',
 'SRR-200708',
 'STI',
 'STJ-201701',
 'STO-199811',
 'SUN-201210',
 'SVU',
 'SWK',
 'SYY',
 'T',
 'T-200511',
 'TA-199907',
 'TAP',
 'TCOMA-199903',
 'TDM-199708',
 'TEK-200711',
 'TEN',
 'TGNA',
 'TGT',
 'THC',
 'THY-199708',
 'TIN-201202',
 'TJX',
 'TKR',
 'TLAB-201312',
 'TMC-200006',
 'TMC.A-200006',
 'TMK',
 'TNB-201205',
 'TOY-200507',
 'TRB-200712',
 'TRV',
 'TRW-200212',
 'TWX-200101',
 'TX-200110',
 'TXN',
 'TXT',
 'TXU-200710',
 'UAWGQ-200303',
 'UCC-199904',
 'UCL-200508',
 'UCM-200010',
 'UIS',
 'UK-200102',
 'UMG-200006',
 'UN',
 'UNH',
 'UNM',
 'UNP',
 'USB-200102',
 'USBC-199708',
 'USH-199706',
 'USHC-199607',
 'USS-199810',
 'UST-200901',
 'USW-200006',
 'UTX',
 'VAT-199609',
 'VFC',
 'VO-200012',
 'VZ',
 'WAI-199808',
 'WB-200108',
 'WB-200812',
 'WBA',
 'WEN-200809',
 'WFC',
 'WFC-199811',
 'WHR',
 'WLA-200006',
 'WLL-200203',
 'WMB',
 'WMT',
 'WMX-199807',
 'WNDXQ-200611',
 'WOR',
 'WWY-200810',
 'WY',
 'WYE-200910',
 'X',
 'XEL',
 'XOM',
 'XRX',
 'YRCW']

In [26]:
# Replace SYMBOL-yyyymm with SYMBOL.
df['tickers'] = [[ticker.split('-')[0] for ticker in tickers] for tickers in df['tickers']]
df.head()

                                                      tickers
date
1996-01-02  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-03  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-04  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-10  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-11  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...

In [27]:
l = list(df['tickers'].tail(1))[0]
len(l)

504

In [28]:
# Add LIN after 2018-10-31
df.loc[df.index > '2018-10-31', 'tickers'].apply(lambda x: x.append('LIN'))
'LIN' in df['tickers'].values[-1]

True

In [29]:
# Remove duplicates in each row.
df['tickers'] = [sorted(list(set(tickers))) for tickers in df['tickers']]
df.tail()
# num = []
# for i, row in df.iterrows():
#     l = list(row['tickers'])
#     num.append(len(l))
#     print(i, len(l))
# pd.Series(num).describe()

                                                      tickers
date
2019-01-03  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-08  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-09  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-10  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-11  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...

In [30]:
l = list(df['tickers'].head(3100))[1500]
len(l)

498

Changes to the list of S&P 500 components
https://en.wikipedia.org/wiki/List_of_S%26P_500_companies#Selected_changes_to_the_list_of_S&P_500_components

In [31]:
# Read S&P 500 changes csv file.
filename = 'sp500_changes_since_2019.csv'
changes = get_table(filename)

# Convert ticker column from csv to list, then sort.
changes['add'] = changes['add'].apply(lambda x: sorted(x.split(',')))
changes['remove'] = changes['remove'].apply(lambda x: sorted(x.split(',')))
changes

                                add                remove
date
2019-01-18                    [TFX]                 [PCG]
2019-02-15                    [ATO]                 [NFX]
2019-02-27                    [WAB]                  [GT]
2019-04-02                    [DOW]                 [BHF]
2019-06-01                    [LHX]                 [HRS]
2019-06-03               [CTVA, DD]           [DWDP, FLR]
2019-06-07                   [AMCR]                 [MAT]
2019-07-01                   [MKTX]                 [LLL]
2019-07-15                   [TMUS]                 [RHT]
2019-08-08                     [GL]                 [TMK]
2019-08-09              [IEX, LDOS]             [APC, FL]
2019-09-23                    [CDW]                 [TSS]
2019-09-26                    [NVR]                 [JEF]
2019-10-03                    [LVS]                [NKTR]
2019-10-18                    [BKR]                [BHGE]
2019-11-05             [NLOK, PEAK]           [HCP, SYMC]
2019-11-21                    [NOW]                [CELG]
2019-12-05              [VIAC, WRB]           [CBS, VIAB]
2019-12-09              [ODFL, TFC]            [BBT, STI]
2019-12-10                      [J]                 [JEC]
2019-12-23         [LYV, STE, ZBRA]      [AMG, MAC, TRIP]
2020-01-28                   [PAYC]                 [WCG]
2020-03-03                     [TT]                 [XEC]
2020-04-03        [CARR, OTIS, RTX]                 [UTX]
2020-04-06                    [HWM]        [ARNC, M, RTN]
2020-05-12              [DPZ, DXCM]           [AGN, CPRI]
2020-05-22                    [WST]                  [HP]
2020-06-22          [BIO, TDY, TYL]       [ADS, HOG, JWN]
2020-09-18                   [LUMN]                 [CTL]
2020-09-21        [CTLT, ETSY, TER]      [COTY, HRB, KSS]
2020-10-07                   [POOL]                [ETFC]
2020-10-12                    [VNT]                 [NBL]
2020-11-17                   [VTRS]                 [MYL]
2020-12-21                   [TSLA]                 [AIV]
2021-01-07                   [ENPH]                 [TIF]
2021-01-21                   [TRMB]                 [CXO]
2021-02-12                   [MPWR]                 [FTI]
2021-03-22  [CZR, GNRC, NXPI, PENN]  [FLS, SLG, VNT, XRX]
2021-04-20                    [PTC]                 [VAR]
2021-05-14                    [CRL]                [FLIR]
2021-06-04                    [OGN]                 [HFC]
2021-07-21                   [MRNA]                [ALXN]
2021-08-03                   [BBWI]                  [LB]
2021-08-30                   [TECH]                [MXIM]
2021-09-20        [BRO, CDAY, MTCH]      [NOV, PRGO, UNM]
2021-10-04                   [CTRA]                 [COG]
2021-12-14                   [EPAM]                 [KSU]
2021-12-20        [FDS, SBNY, SEDG]        [HBI, LEG, WU]
2022-01-20                    [WTW]                [WLTW]
2022-02-02                    [CEG]                 [GPS]
2022-02-15                   [NDSN]                [XLNX]
2022-02-17                   [PARA]                [VIAC]
2022-03-02                    [MOH]                [INFO]
2022-04-04                    [CPT]                [PBCT]
2022-04-11                    [WBD]        [DISCA, DISCK]
2022-05-10                   [BALL]                 [BLL]
2022-06-08                   [VICI]                [CERN]
2022-06-09                   [META]                  [FB]
2022-06-21                     [ON]                [IPGP]
2022-06-21                    [KDP]             [UA, UAA]
2022-06-28                    [ELV]                [ANTM]
2022-09-19             [CSGP, INVH]           [PENN, PVH]
2022-10-03               [EQT, PCG]           [CTXS, DRE]
2022-10-12                   [TRGP]                [NLSN]

In [34]:
# Copy the last row in dataframe, modify for changes, then append.
for change in changes.itertuples():

    new_row = df.tail(1)
    
    tickers = list(new_row['tickers'][0])
    tickers += change.add
    tickers = list(set(tickers) - set(change.remove))
    tickers = sorted(tickers)
    
    d = {'date':change.Index, 'tickers':[tickers]}
    new_entry = pd.DataFrame(d)
    new_entry.set_index('date', inplace=True)
    df1 = df.append(new_entry)

C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)
C:\Users\broug\AppData\Local\Temp\ipykernel_2856\4004052228.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(new_entry)

In [33]:
df1.tail()

                                                      tickers
date
2019-01-08  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-09  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-10  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-11  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2022-10-12  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...

In [16]:
# compare last row to current S&P500 list
filename = 'sp500.csv'
current = pd.read_csv(filename)
current = list(current['Symbol'])
last_entry = list(df['tickers'][-1])

diff = list(set(current) - set(last_entry)) + list(set(last_entry) - set(current))
diff

[]

In [17]:
# Convert tickers column back to csv.
df['tickers'] = df['tickers'].apply(lambda x: ",".join(x))
df.head()

                                                      tickers
date
1996-01-02  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
1996-01-03  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
1996-01-04  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
1996-01-10  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
1996-01-11  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...

In [18]:
now = datetime.now()
dt_string = now.strftime('%m-%d-%Y') # mm-dd-YYYY
filename = 'S&P 500 Historical Components & Changes({}).csv'.format(dt_string)
df.to_csv(filename)

In [35]:
df

                                                      tickers
date
1996-01-02  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-03  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-04  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-10  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
1996-01-11  [AAL, AAMRQ, AAPL, ABI, ABS, ABT, ABX, ACKH, A...
...                                                       ...
2019-01-03  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-08  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-09  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-10  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...
2019-01-11  [A, AAL, AAP, AAPL, ABBV, ABC, ABMD, ABT, ACN,...

[2595 rows x 1 columns]